SignalR Ticket Sample/SignalR Ticket Sample/Controllers/AdminController.cs
using System.Linq;
using System.Web.Mvc;
using SignalRTicketSample.Hubs;
using SignalRTicketSample.Models;

namespace SignalRTicketSample.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StartEvent(int secondsToStart, int quantityAvailable)
        {
            var eventItem = HomeController.GetEvents().First();
            var ticketEngine = TicketEngine.StartEvent(eventItem.Id, secondsToStart, quantityAvailable);
            TicketHub.TicketEngine = ticketEngine;

            return RedirectToAction("Status");
        }

        public ActionResult Status()
        {
            return View();
        }
    }
}

SignalR Ticket Sample/SignalR Ticket Sample/Views/Admin/Index.cshtml
<h2>Start New Ticket Event</h2>

<form action="@Url.Action("StartEvent", "Admin")" method="POST">
    <label for="secondsToStart">Enter the seconds to wait before starting:</label>
    <input type="number" name="secondsToStart" />
    <label for="secondsToStart">Enter the quantity of tickets available:</label>
    <input type="number" name="quantityAvailable" />
    <br/>
    <button type="submit">Start</button>
</form>

SignalR Ticket Sample/SignalR Ticket Sample/Views/Admin/Status.cshtml
<h2>Event Status</h2>
<div id="registrationInformation">
    <div class="spinnerContainer">
        Please wait while we fetch the registration information for this event.
        <br />
        <img src="~/Images/ajax-loader.gif" alt="Loading" />
    </div>
    <div id="timerContainer" style="display: none;">
        Ticket registration for this event will open up in <span id="remainingSecondsSpan"></span>&nbsp;seconds.
    </div>
    <div id="reservationContainer" style="display: none;">
        <p>Registration is now open!</p>
    </div>
</div>
<div class="clear-fix"></div>
<div>
    <h3>Active Connections</h3>
    <ul id="connectionsList"></ul>
</div>
<div>
    <h3>Registration Holds</h3>
    <ul id="registrationHoldsList"></ul>
</div>
<div>
    <h3>Registration Queue</h3>
    <ul id="registrationQueueList"></ul>
</div>
<div>
    <h3>Completed Registrations</h3>
    <ul id="completedList"></ul>
</div>